language: python
python:
  - '3.8'
  - '3.7'
jobs:
  fast_finish: true
  include:
    - python: "3.8"
      env: TOXENV=lint
    - python: "3.8"
      env: TOXENV=cov
      after_success: coveralls
    - python: "3.7"
      env: TOXENV=py37
    - python: "3.8"
      env: TOXENV=py38
install: pip install -U tox coveralls
script: tox